#' @title compute.power
#'
#' @description Compute the power and effect size for the object obtained from \link{get.stats}.
#'
#' @param power4peaks.stats An object of class \code{power4peaks.stats}.
#' @param sample.size.range Numeric vector of length 2, indicating minimum and maximum of the range of number of samples in which test the power. Default: \code{c(0,50)}.
#' @param power.threshold number between 0 and 1 indicating the threshold to plot for the power. Default: \code{0.8} (80 percent power).
#' @param estimation.method String indicating the method to use to estimate the power (passed to \code{SSPA::sampleSize} function). One among: 'deconv', 'congrad', 'tikhonov' or 'ferreira'. Default: \code{"congrad"}.
#' @param distribution.type String indicating the type of distribution to use; one among: 'norm', 't', 'f', 'chisq'. Default: \code{NULL}, automatically defined from the power4peaks.stats object.
#' @param df Numeric value or vector (df1 and df2, required only for F-statistics) indicating the number of degrees of freedom. Default: \code{NULL}, automatically defined from the power4peaks.stats object.
#' @param power.threshold.line.color String indicating any R-supported color to use for the power threshold line.
#'
#' @import ggplot2
#' @importFrom ggpubr theme_pubr
#' @importFrom ggtext element_markdown
#  @import SSPA
#'
#' @return An object of class \code{power4peaks.power}.

#' @export compute.power


compute.power =
  function(power4peaks.stats,
           sample.size.range = c(0, 20),
           power.threshold = 0.8,
           estimation.method = "congrad",
           distribution.type = NULL,
           df = NULL,
           power.threshold.line.color = "firebrick") {

    # ### libraries
    # require(ggplot2)

    # SSPA installation
    if (!requireNamespace("SSPA", quietly = TRUE)) {
      warning("The 'SSPA' (Bioconductor) package must be installed to use this function.")

      ### Ask for installing
      install = readline("Do you want to install `SSPA`? [yes/no] ")
      if (tolower(install) %in% c("yes","y","yeah","yep","yo","ya")) {
        install.packages("https://www.bioconductor.org/packages/3.12/bioc/src/contrib/SSPA_2.30.0.tar.gz", type = "source")
        library(SSPA)
      }
    } else {
      require(SSPA)
    }



    ### Check object
    if (!("power4peaks.stats" %in% class(power4peaks.stats))) {
      stop("The `power4peaks.stats` object must be of class power4peaks.stats, as generated by `get.stats` or `as.power4peaks` function.")
    }



    ########
    ## define SSPA parameters
    if (is.null(distribution.type)) {
      distribution.type = power4peaks.stats@stat.distribution
    } else {
      if (!(tolower(distribution.type) %in% c("norm", "t", "f", "chisq"))){
        stop("The `distribution.type` must be one among: 'norm', 't', 'f', 'chisq'.")
      } else {
        distribution.type = tolower(distribution.type)
      }
    }


    if (is.null(df)) {
      if (!is.null(power4peaks.stats@df2)) {
        df = c(power4peaks.stats@df1, power4peaks.stats@df2)
      } else {
        df = power4peaks.stats@df1
      }
    } else {
      if (tolower(distribution.type) == "f" & length(df) != 2) {
        stop("When `distribution.type` is set to 'FALSE', the df must be a vector of two elements: c(numerator.df1, denominator.df2).")
      }
    }


    ### Computing sample-size
    # Getting n samples in each group of the contrast
    n.group1 = sum(power4peaks.stats@dba.object$samples[,power4peaks.stats@contrast[1]] %in% power4peaks.stats@contrast[2], na.rm = TRUE)
    n.group2 = sum(power4peaks.stats@dba.object$samples[,power4peaks.stats@contrast[1]] %in% power4peaks.stats@contrast[3], na.rm = TRUE)


    if (distribution.type %in% c("norm")) {
      # effective sample size defined as: sqrt(1/(1/n1 + 1/n2))
      sample.size = sqrt(1 / (1/n.group1 + 1/n.group2))
    } else if (distribution.type %in% c("chisq")) {
      # Total sample size
      sample.size = n.group1 + n.group2
    } else {
      # Total sample size
      sample.size = n.group1 + n.group2
    }



    # Run SSPA analyses
    pd = SSPA:::pilotData(statistics = power4peaks.stats@statistics,
                          samplesize = sample.size,
                          distribution = distribution.type,
                          df = df)


    ss = SSPA::sampleSize(PilotData = pd,
                          method = estimation.method,
                          control = list(from = sample.size.range[1], to = sample.size.range[2]))


    test_sample_sizes = seq(ifelse(sample.size.range[1] < 0, yes = 0, no = sample.size.range[1]), sample.size.range[2], 1)
    pwr = SSPA::predictpower(ss, samplesizes = test_sample_sizes, plot = F)



    ####################################
    ### plotting
    title_lable = ifelse(test = distribution.type == "f",
                         yes = paste0("Method: **", power4peaks.stats@diff.method, "** (*df:* ",df, ")"),
                         no = paste0("Method: **", power4peaks.stats@diff.method, "** (*df1:* ",df[1], ", *df2:* ",df[2],")"))


    effect_size_plot =
      ggplot(data = data.frame(effect_size = ss@theta,
                               Lamba = ss@lambda),
             aes(x = effect_size,
                 y = Lamba)) +
      geom_line(linewidth = 1) +
      geom_vline(xintercept = sum(power4peaks.stats@dba.object$samples[,power4peaks.stats@contrast[1]] %in% power4peaks.stats@contrast[2:3])/2, linetype = 3, color = "gray50") +
      xlab("Effect Size (theta)") +
      xlim(c(0,NA)) +
      ggtitle(label = title_lable,
              subtitle = paste0("*",power4peaks.stats@contrast[1],":* **", power4peaks.stats@contrast[2], "** *vs* **",power4peaks.stats@contrast[3],"**")) +
      annotate(geom = "text", x = +Inf, y = +Inf, label = bquote('\u03C0'^0 ~ "=" ~ .(round(ss@pi0, 2))), hjust = 1.5, vjust = 1.5) +
      ggpubr::theme_pubr() +
      theme(axis.text = element_text(color = "black"),
            axis.ticks = element_line(color = "black"),
            plot.title = ggtext::element_markdown(hjust = 0.5),
            plot.subtitle = ggtext::element_markdown(hjust = 0.5))



    power_plot =
      ggplot(data = data.frame(sample_size = test_sample_sizes,
                               Power = pwr),
             aes(x = sample_size,
                 y = Power)) +
      geom_line(linewidth = 1) +
      xlab("Sample size (per group)") +
      theme_classic() +
      geom_vline(xintercept = sum(power4peaks.stats@dba.object$samples[,power4peaks.stats@contrast[1]] %in% power4peaks.stats@contrast[2:3])/2, linetype = 3, color = "gray50") +
      geom_hline(yintercept = power.threshold, linetype = 1, color = power.threshold.line.color) +
      scale_y_continuous(limits = c(0,1), expand = c(0,0)) +
      ggpubr::theme_pubr()



    ### Export object
    power4peaks.power =
      new(Class = "power4peaks.power",
          pilot.data = pd,
          sample.size = ss,
          power = list(test.sample.sizes = test_sample_sizes,
                       power = pwr),
          effect.size.plot = effect_size_plot,
          power.plot = power_plot)

    return(power4peaks.power)

  } # END function
