#' @title compute.power
#'
#' @description Compute the power and effect size for the object obtained from \link{get.stats}.
#'
#' @param power4omics.stats An object of class \code{power4omics.stats}.
#' @param sample.size.range Numeric vector of length 2, indicating minimum and maximum of the range of number of samples in which test the power. Default: \code{c(0,50)}.
#' @param power.threshold number between 0 and 1 indicating the threshold to plot for the power. Default: \code{0.8} (80 percent power).
#' @param distribution.type String indicating the type of distribution to use; one among: 'norm', 't', 'f', 'chisq'. Default: \code{NULL}, automatically defined from the power4omics.stats object.
#' @param distribution.type Integer indicating the number of degrees of freedom. Default: \code{NULL}, automatically defined from the power4omics.stats object.
#'
#' @return An object of class \code{power4omics.power}.

#' @export compute.power


compute.power =
  function(power4omics.stats,
           sample.size.range = c(0, 50),
           power.threshold = 0.8,
           distribution.type = NULL,
           df = NULL) {

    ### libraries
    # SSPA installation
    if (!requireNamespace("SSPA", quietly = TRUE)) {
      warning("The 'SSPA' (Bioconductor) package must be installed to use this function.")

      ### Ask for installing
      install = readline("Do you want to install `SSPAR`? [yes/no] ")
      if (tolower(install) %in% c("yes","y","yeah","yep","yo")) {
        devtools::install_url("https://github.com/sebastian-gregoricchio/power4omics/resources/SSPA_2.30.0.tar.gz", type = "source")
        library(SSPA)
      }
    } else {
      require(SSPA)
    }


    ### Check object
    if (!("power4omics.stats" %in% class(power4omics.stats))) {
      warning("The 'power4omics.stats' object must be of class power4omics.stats, as generated by `get.stats` function.")
      return()
    }



    ########
    ## define SSPA parameters
    if (is.null(distribution.type)) {distribution.type = power4omics.stats@stat.distribution}
    if (is.null(df)) {df = power4omics.stats@df}



    # Run SSPA analyses
    pd = SSPA:::pilotData(statistics = power4omics.stats@statistics,
                          samplesize = sum(power4omics.stats@dba.object$samples[,power4omics.stats@contrast[1]] %in% power4omics.stats@contrast[2:3]),
                          distribution = distribution.type,
                          df = df)

    ss = SSPA::sampleSize(PilotData = pd,
                          method = "congrad",
                          control = list(from = sample.size.range[1], to = sample.size.range[2]))


    test_sample_sizes = seq(ifelse(sample.size.range[1] < 0, yes = 0, no = sample.size.range[1]), sample.size.range[2], 1)
    pwr = SSPA::predictpower(ss, samplesizes = test_sample_sizes, plot = F)



    ####################################
    ### plotting
    effect_size_plot =
      ggplot(data = data.frame(effect_size = ss@theta,
                               Lamba = ss@lambda),
             aes(x = effect_size,
                 y = Lamba)) +
      geom_line() +
      geom_vline(xintercept = sum(power4omics.stats@dba.object$samples[,power4omics.stats@contrast[1]] %in% power4omics.stats@contrast[2:3]), linetype = 3, color = "gray50") +
      xlab("Effect Size (theta)") +
      xlim(c(0,NA)) +
      ggtitle(label = paste0("Method: **", power4omics.stats@diff.method, "** (*df:* ",df, ")"),
              subtitle = paste0("*",power4omics.stats@contrast[1],"*: **", power4omics.stats@contrast[2], "** *vs* **",power4omics.stats@contrast[3],"**")) +
      ggpubr::theme_pubr() +
      theme(axis.text = element_text(color = "black"),
            axis.ticks = element_line(color = "black"),
            plot.title = ggtext::element_markdown(hjust = 0.5),
            plot.subtitle = ggtext::element_markdown(hjust = 0.5))



    power_plot =
      ggplot(data = data.frame(sample_size = test_sample_sizes,
                               Power = pwr),
             aes(x = sample_size,
                 y = Power)) +
      geom_line(linewidth = 1) +
      xlab("Sample size") +
      theme_classic() +
      geom_vline(xintercept = sum(power4omics.stats@dba.object$samples[,power4omics.stats@contrast[1]] %in% power4omics.stats@contrast[2:3]), linetype = 3, color = "gray50") +
      geom_hline(yintercept = power.threshold, linetype = 1, color = "firebrick") +
      scale_y_continuous(limits = c(0,1), expand = c(0,0)) +
      ggpubr::theme_pubr()



    ### Export object
    power4omics.power =
      new(Class = "power4omics.power",
          pilot.data = pd,
          sample.size = ss,
          power = list(test.sample.sizes = test_sample_sizes,
                       power = pwr),
          effect.size.plot = effect_size_plot,
          power.plot = power_plot)

    return(power4omics.power)

  } # END function
