#' @title plot.stat.distribution
#'
#' @description Plot the distribution of the statistics obtained from \link{get.stats}. Normal and chi-squared distributions are overlayed.
#'
#' @param power4omics.stats An object of class \code{power4omics.stats}.
#' @param obs.stat.color Any R-supported color string indicating the color to use for the observed statistics distribution. Default: \code{"black"}.
#' @param norm.fit.color Any R-supported color string indicating the color to use for the normal distribution. Default: \code{"firebrick"}.
#' @param chi.fit.color Any R-supported color string indicating the color to use for the chi-squared distribution. Default: \code{"firebrick"}.
#'
#' @return A ggplot object.

#' @export plot.stat.distribution


plot.stat.distribution =
  function(power4omics.stats,
           obs.stat.color = "black",
           norm.fit.color = "firebrick",
           #t.fit.color = "violet",
           chi.fit.color = "navy") {

    ### libraries
    require(fitdistrplus)
    require(ggplot2)
    require(dplyr)


    ### Check object
    if (!("power4omics.stats" %in% class(power4omics.stats))) {
      warning("The 'power4omics.stats' object must be of class power4omics.stats, as generated by `get.stats` function.")
      return()
    }


    ### Fit distributions
    fit_norm = fitdist(power4omics.stats@statistics, "norm")
    fit_chisq = fitdist(power4omics.stats@statistics, "chisq", start = list(df = power4omics.stats@df))
    #fit_t = fitdist(power4omics.stats@statistics, "t", start = list(df = power4omics.stats@df))

    pdf(NULL)
    distributions = invisible(fitdistrplus::denscomp(list(fit_norm,
                                                          #fit_t,
                                                          fit_chisq),
                                                     legendtext = c("norm",
                                                                    #"t",
                                                                    "chisq")))
    invisible(dev.off())

    ### get observed statistics distribution
    obs_density = density(power4omics.stats@statistics)
    x_range = range(obs_density$x)

    ### Combine statistics values
    plotting_tb =
      do.call(rbind,
              list(data.frame(Statistics = obs_density$x,
                              Density = obs_density$y,
                              Distribution = "Observed"),
                   data.frame(Statistics = seq(from = x_range[1], to = x_range[2], length.out = nrow(distributions$densities)),
                              Density = distributions$densities[,1],
                              Distribution = "Normal"),
                   # data.frame(Statistics = seq(from = x_range[1], to = x_range[2], length.out = nrow(distributions$densities)),
                   #            Density = distributions$densities[,3],
                   #            Distribution = "t")),
                   data.frame(Statistics = seq(from = x_range[1], to = x_range[2], length.out = nrow(distributions$densities)),
                              Density = distributions$densities[,2],
                              Distribution = "\u03C7\u00B2"))) %>%
      dplyr::mutate(Distribution = factor(Distribution, levels = c("Observed",
                                                                   "Normal",
                                                                   #"t",
                                                                   "\u03C7\u00B2")))


    density_plot =
      ggplot(plotting_tb,
             aes(x = Statistics,
                 y = Density,
                 color = Distribution,
                 linewidth = Distribution,
                 linetype = Distribution)) +
      geom_line() +
      scale_linetype_manual(values = c("Observed" = 1,
                                       "Normal" = 2,
                                       #"t" = 2,
                                       "\u03C7\u00B2" = 2)) +
      scale_linewidth_manual(values = c("Observed" = 1,
                                        "Normal" = 0.5,
                                        #"t" = 0.5,
                                        "\u03C7\u00B2" = 0.5)) +
      scale_color_manual(values = c("Observed" = obs.stat.color,
                                    "Normal" = norm.fit.color,
                                    #"t" = t.fit.color,
                                    "\u03C7\u00B2" = chi.fit.color)) +
      ggtitle(label = paste0("Method: **", power4omics.stats@diff.method, "** (*df:* ",power4omics.stats@df, ")"),
              subtitle = paste0("*",power4omics.stats@contrast[1],"*: **", power4omics.stats@contrast[2], "** *vs* **",power4omics.stats@contrast[3],"**")) +
      ggpubr::theme_pubr() +
      theme(legend.position = "right",
            plot.title = ggtext::element_markdown(hjust = 0.5),
            plot.subtitle = ggtext::element_markdown(hjust = 0.5),
            aspect.ratio = 0.5)

    return(density_plot)
  } # END function
