#' @title plot.stat.distribution
#'
#' @description Plot the distribution of the statistics obtained from \link{get.stats}. Normal and chi-squared distributions are overlayed.
#'
#' @param power4peaks.stats An object of class \code{power4peaks.stats}.
#' @param obs.stat.color Any R-supported color string indicating the color to use for the observed statistics distribution. Default: \code{"black"}.
#' @param norm.fit.color Any R-supported color string indicating the color to use for the normal distribution. Default: \code{"firebrick"}.
#' @param chi.fit.color Any R-supported color string indicating the color to use for the chi-squared distribution. Default: \code{"navy"}.
#' @param t.fit.color Any R-supported color string indicating the color to use for the t distribution. Default: \code{"violet"}.
#' @param f.fit.color Any R-supported color string indicating the color to use for the F distribution. Default: \code{"forestgreen"}.
#' @param df1 Numeric value forcing the value for the degrees-of-freedom 1. Default: \code{NULL} (the value is obtained from the \code{power4peaks.stats} object.
#' @param df2 Numeric value forcing the value for the degrees-of-freedom 2. Default: \code{NULL} (the value is obtained from the \code{power4peaks.stats} object.
#' @param adapt.y.axis Logical value indicating whether the Y-axis should be scaled to fit the observed distribution/ Default: \code{TRUE}.
#'
#'
#' @return A ggplot object.

#' @export plot.stat.distribution


plot.stat.distribution =
  function(power4peaks.stats,
           obs.stat.color = "black",
           norm.fit.color = "firebrick",
           chi.fit.color = "navy",
           t.fit.color = "violet",
           f.fit.color = "forestgreen",
           df1 = NULL,
           df2 = NULL,
           adapt.y.axis = TRUE) {

    ### libraries
    require(fitdistrplus)
    require(ggplot2)
    require(dplyr)


    ### Check object
    if (!("power4peaks.stats" %in% class(power4peaks.stats))) {
      warning("The `power4peaks.stats` object must be of class power4peaks.stats, as generated by `get.stats` function.")
      return()
    }


    ## Check the degrees of freedom
    if (is.null(df1)) {DF1 = power4peaks.stats@df1} else {DF1 = df1}
    if (is.null(df2)) {DF2 = power4peaks.stats@df2} else {DF2 = df2}


    ### Fit distributions
    fit_norm = fitdist(power4peaks.stats@statistics, "norm")
    fit_chisq = fitdist(power4peaks.stats@statistics, "chisq", start = list(df = DF1))
    fit_t = fitdist(power4peaks.stats@statistics, "t", start = list(df = DF1))
    if (!is.null(DF2)) {
      fit_f = fitdist(power4peaks.stats@statistics, "f", start = list(df1 = DF1, df2 = DF2))
    }


    pdf(NULL)
    if (!is.null(DF2)) {
      distributions = invisible(fitdistrplus::denscomp(list(fit_norm,
                                                            fit_chisq,
                                                            fit_t,
                                                            fit_f),
                                                       legendtext = c("norm",
                                                                      "chisq",
                                                                      "t",
                                                                      "F")))
    } else {
      distributions = invisible(fitdistrplus::denscomp(list(fit_norm,
                                                            fit_chisq,
                                                            fit_t),
                                                       legendtext = c("norm",
                                                                      "chisq",
                                                                      "t")))
    }

    invisible(dev.off())

    ### get observed statistics distribution
    obs_density = density(power4peaks.stats@statistics)
    x_range = range(obs_density$x)

    ### Combine statistics values
    plotting_tb =
      do.call(rbind,
              list(data.frame(Statistics = obs_density$x,
                              Density = obs_density$y,
                              Distribution = "Observed"),
                   data.frame(Statistics = seq(from = x_range[1], to = x_range[2], length.out = nrow(distributions$densities)),
                              Density = distributions$densities[,1],
                              Distribution = "Normal"),
                   data.frame(Statistics = seq(from = x_range[1], to = x_range[2], length.out = nrow(distributions$densities)),
                              Density = distributions$densities[,2],
                              Distribution = "\u03C7\u00B2"),
                   data.frame(Statistics = seq(from = x_range[1], to = x_range[2], length.out = nrow(distributions$densities)),
                              Density = distributions$densities[,3],
                              Distribution = "t"))) %>%
      dplyr::mutate(Distribution = factor(Distribution, levels = c("Observed",
                                                                   "Normal",
                                                                   "\u03C7\u00B2",
                                                                   "t")))


    if (is.null(DF2)) {
      plotting_tb =
        plotting_tb %>%
        dplyr::mutate(Distribution = factor(Distribution, levels = c("Observed",
                                                                     "Normal",
                                                                     "\u03C7\u00B2",
                                                                     "t")))

    } else { # including F-distribution
      plotting_tb =
        rbind(plotting_tb,
              data.frame(Statistics = seq(from = x_range[1], to = x_range[2], length.out = nrow(distributions$densities)),
                         Density = distributions$densities[,4],
                         Distribution = "F")) %>%
        dplyr::mutate(Distribution = factor(Distribution, levels = c("Observed",
                                                                     "Normal",
                                                                     "\u03C7\u00B2",
                                                                     "t",
                                                                     "F")))
    }


    ### get maximum height for plotting (sometimes the fitting at low-tail is too high)
    max_observed = max((plotting_tb %>% dplyr::filter(Distribution == "Observed"))$Density, na.rm = T)



    if (is.null(DF2)) {
      density_plot =
        ggplot(plotting_tb,
               aes(x = Statistics,
                   y = Density,
                   color = Distribution,
                   linewidth = Distribution,
                   linetype = Distribution)) +
        geom_line() +
        scale_linetype_manual(values = c("Observed" = 1,
                                         "Normal" = 2,
                                         "t" = 2,
                                         "\u03C7\u00B2" = 2)) +
        scale_linewidth_manual(values = c("Observed" = 1,
                                          "Normal" = 0.5,
                                          "t" = 0.5,
                                          "\u03C7\u00B2" = 0.5)) +
        scale_color_manual(values = c("Observed" = obs.stat.color,
                                      "Normal" = norm.fit.color,
                                      "t" = t.fit.color,
                                      "\u03C7\u00B2" = chi.fit.color)) +
        ggtitle(label = paste0("Method: **", power4peaks.stats@diff.method, "** (*df:* ",DF1, ")"),
                subtitle = paste0("*",power4peaks.stats@contrast[1],"*: **", power4peaks.stats@contrast[2], "** *vs* **",power4peaks.stats@contrast[3],"**")) +
        ggpubr::theme_pubr() +
        theme(legend.position = "right",
              plot.title = ggtext::element_markdown(hjust = 0.5),
              plot.subtitle = ggtext::element_markdown(hjust = 0.5),
              aspect.ratio = 0.5)

    } else { # including F-distribution
      density_plot =
        ggplot(plotting_tb,
               aes(x = Statistics,
                   y = Density,
                   color = Distribution,
                   linewidth = Distribution,
                   linetype = Distribution)) +
        geom_line() +
        scale_linetype_manual(values = c("Observed" = 1,
                                         "Normal" = 2,
                                         "t" = 2,
                                         "F" = 2,
                                         "\u03C7\u00B2" = 2)) +
        scale_linewidth_manual(values = c("Observed" = 1,
                                          "Normal" = 0.5,
                                          "t" = 0.5,
                                          "F" = 0.5,
                                          "\u03C7\u00B2" = 0.5)) +
        scale_color_manual(values = c("Observed" = obs.stat.color,
                                      "Normal" = norm.fit.color,
                                      "t" = t.fit.color,
                                      "F" = f.fit.color,
                                      "\u03C7\u00B2" = chi.fit.color)) +
        ggtitle(label = paste0("Method: **", power4peaks.stats@diff.method, "** (*df1:* ",DF1, ", *df2:* ",DF2, ")"),
                subtitle = paste0("*",power4peaks.stats@contrast[1],"*: **", power4peaks.stats@contrast[2], "** *vs* **",power4peaks.stats@contrast[3],"**")) +
        ggpubr::theme_pubr() +
        theme(legend.position = "right",
              plot.title = ggtext::element_markdown(hjust = 0.5),
              plot.subtitle = ggtext::element_markdown(hjust = 0.5),
              aspect.ratio = 0.5)
    }


    ### export object
    if (isTRUE(adapt.y.axis)) {
      return(density_plot + coord_cartesian(ylim = c(0, max_observed*1.5)))
    } else {
      return(density_plot)
    }

  } # END function
