name: codecov

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Run test coverage
        run: Rscript -e 'covr::codecov(token = Sys.getenv("CODECOV_TOKEN"))'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
